### ISSUE TITLE
Release should trigger a binary build

### ISSUE THREAD

**Issue by haani-niyaz** [rog-golang-buddies/golang-template-repository#27]
so my limited knowledge of gitlab actions tells me that this should have created a binary:

```
name: SLSA Go releaser
on:
  workflow_dispatch:
  release:
    types: [created]
```

from https://github.com/rog-golang-buddies/golang-template-repository/blob/main/.github/workflows/go-ossf-slsa3-publish.yml#L17

there is a release but this workflow didn't get triggered. I suspect for this to fire, the release type needs to be `published` as shown below:

```
on:
  release:
    types: [published]
```

Without testing I can't be sure.

On a slightly different note, I'm also not familiar with SLSA Go releaser and that makes me hesitant to provide it as a solution to our user base, as we should have some level of authoritative knowledge to support it. In contrast goreleaser appears to be easy to adopt, well documented and is widely used (https://goreleaser.com/users/). 

From a security posture perspective slsa-go might be well worth exploring but I wonder if it is suitable for our first release? perhaps it should be an improvement story. Happy to be corrected but this is my sentiment atm.

CC: @shukra-in-spirit , @pallasite99

**Comment by pallasite99** [comment]
Understood @haani-niyaz 
My understanding was that this would readily publish a go package here which seems to not be the case.

I will be returning from a short trip on Sunday and I’ll create a new PR with the original intended workflow planned.

**Comment by pallasite99** [comment]
@haani-niyaz I've created this PR to delete the SLSA releaser and instead introduce the original intended workflow:

https://github.com/rog-golang-buddies/golang-template-repository/pull/31
