### ISSUE TITLE
Downgrade v1.0.0 release

### ISSUE THREAD

**Issue by haani-niyaz** [rog-golang-buddies/golang-template-repository#37]
The release `v1.0.0` was automatically tagged via the semantic-release workflow when it was merged to master (semantic-release default start tag is `v1.0.0`). `v1.0.0` represents a stable production ready release and this repo isn't there yet. We should downgrade the release to `v0.1.0` as it better represents the state of the repo. 

Actions required:
1. Delete `v1.0.0` release and tag
2. Create a new tag and release `v0.1.0` via UI

**Comment by shukra-in-spirit** [comment]
completed

**Comment by shukra-in-spirit** [comment]
After downgrading, the new releases are no longer being created with every merge to the main branch. Is this something that will start after the first major release of v1.0.0 or is there some other issue in the workflow?

**Comment by haani-niyaz** [comment]
@shukra-in-spirit this is by design. semantic-release requires a commit message convention to be followed to trigger releases. I was planning on sharing this with the team today to cover this:

https://github.com/rog-golang-buddies/golang-template-repository/wiki/Platform-Team-Onboarding-Guide#repository-releases
