### ISSUE TITLE
Refresh README

### ISSUE THREAD

**Issue by haani-niyaz** [rog-golang-buddies/golang-template-repository#44]
The currently README is out of date and should be updated to give an intro into how to navigate this repo. Namely, it should provide:

1. A basic README structure since the bulk of the content will be hosted in gh-pages
2. A [link](https://rog-golang-buddies.github.io/golang-template-repository/) to this repo's gh-pages site so that users are aware of how to get started.

**Comment by jmaister** [comment]
Also, I think that the README.md will be overwritten by the projects, so all the info could be lost.

I propose to have a TEMPLATE.md and make a reference from the README.md

```markdown
# Template

This project has been created using [](https://github.com/rog-golang-buddies/golang-template-repository)
Check for more info on [docs/TEMPLATE.md](TEMPLATE info)
```

**Comment by haani-niyaz** [comment]
@jmaister thanks for the suggestion. 

The README file is to be replaced with the following (hopefully soon):
https://github.com/rog-golang-buddies/golang-template-repository/blob/52ad3bc987f10ba57c529024798a713bd824a4f7/README.md

The idea being that the repo owners take control of the README and we try to leave no footprint of the template repo.
