### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by shukra-in-spirit** [rog-golang-buddies/golang-template-repository#5]
- Add dependabot
- Configure for weekly update scans
- Add necessary description to https://github.com/rog-golang-buddies/README

**Comment by beesaferoot** [comment]
Wouldn't mind taking this up.

**Comment by haani-niyaz** [comment]
hi @beesaferoot, the [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) say that:

> You must store this file in the `.github` directory of your repository. 

We currently have it in `.github/workflows/dependabot.yml`. Is this also an acceptable location or do we need to move it?

**Comment by beesaferoot** [comment]
Updated via #36
