### ISSUE TITLE
Makefile does not work in Windows

### ISSUE THREAD

**Issue by jmaister** [rog-golang-buddies/golang-template-repository#50]
The Makefile contains a call to the "sed" command and it is not available on Windows.

https://github.com/rog-golang-buddies/golang-template-repository/blob/d9937d1ec28ae18d24cf3b0f717c4b992610d411/Makefile#L8

Could this be done in a different way?

**Comment by vancanhuit** [comment]
@jmaister  Did you try to run it in Git Bash?

**Comment by pallasite99** [comment]
@jmaister Could you elaborate on what you mean by 'not available on Windows'?

https://github.com/mbuilov/sed-windows

**Comment by jmaister** [comment]
@vancanhuit Yes, it works on Windows using Git Bash
