### ISSUE TITLE
Add a way to cross-compile builds for multiple OS and Architectures

### ISSUE THREAD

**Issue by pmoieni** [rog-golang-buddies/golang-template-repository#63]
since we don't know which user is using which OS, then executing `go build` or `make build` go will build the binary for that specific OS and Architecture. to avoid that and cross-compile the code we can use `GOOS` and `GOARCH` environment variables inside the `MAKEFILE`.

### examples

Windows 64-bit:
`GOOS=windows GOARCH=amd64 go build -o bin/app-amd64.exe app.go`

Windows 32-bit:
`GOOS=windows GOARCH=386 go build -o bin/app-386.exe app.go`

**Comment by haani-niyaz** [comment]
@pmoieni The next release of the  template repo will include https://goreleaser.com/.  OS/Arch specific binaries will be published on "release". A cli is also available if local testing is necessary. Hope this covers your requirement.

**Comment by haani-niyaz** [comment]
Fixed in `v0.2.0`. Closing.
