### ISSUE TITLE
Create makefile

### ISSUE THREAD

**Issue by shukra-in-spirit** [rog-golang-buddies/golang-template-repository#7]
- Create a makefile with multi service support
- Publish necessary certificates

**Comment by haani-niyaz** [comment]
@vancanhuit, See sample Makefile here:
https://github.com/haani-niyaz/golang-template-repository/blob/add-makefile/Makefile

**Comment by vancanhuit** [comment]
Thanks for sharing @haani-niyaz. I have some thoughts:

- `go mod tidy` also downloads all dependencies so I think we don't need `go mod download`.
- I don't think we need `test-build` at all. Just run `build` is enough to see if it can be built.
